AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy transit gateway
Resources:
  #------------------ TGW
  Tgw:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: "tgw for gitlab poc"
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      DnsSupport: enable
      #MulticastSupport: disable
      VpnEcmpSupport: enable
      Tags:
        - Key: Name
          Value: GitlabS3PoC-Tgw
  TgwAttachClientVpc:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      TransitGatewayId: !Ref Tgw
      VpcId:
        Fn::ImportValue: GitlabS3PoC-ClientVPC-VpcId
      SubnetIds: 
        - Fn::ImportValue: GitlabS3PoC-ClientVPC-PublicSubnet1Id
        - Fn::ImportValue: GitlabS3PoC-ClientVPC-PublicSubnet2Id
      Tags:
        - Key: Name
          Value: GitlabS3PoC-Tgw-ClientVPC
  TgwAttachGitlabVpc:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      TransitGatewayId: !Ref Tgw
      VpcId:
        Fn::ImportValue: GitlabS3PoC-GitlabVPC-VpcId
      SubnetIds: 
        - Fn::ImportValue: GitlabS3PoC-GitlabVPC-PublicSubnet1Id
        - Fn::ImportValue: GitlabS3PoC-GitlabVPC-PublicSubnet2Id
      Tags:
        - Key: Name
          Value: GitlabS3PoC-Tgw-GitlabVPC
  TgwAttachExternalVpc:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      TransitGatewayId: !Ref Tgw
      VpcId:
        Fn::ImportValue: GitlabS3PoC-ExternalVPC-VpcId
      SubnetIds: 
        - Fn::ImportValue: GitlabS3PoC-ExternalVPC-PrivateSubnet1Id
        - Fn::ImportValue: GitlabS3PoC-ExternalVPC-PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: GitlabS3PoC-Tgw-ExternalVPC

  #------------------ Route for VPC
  ClientVpcPrivateSubnet1:
    Type: AWS::EC2::Route
    DependsOn: TgwAttachClientVpc
    Properties:
      RouteTableId:
        Fn::ImportValue: GitlabS3PoC-ClientVPC-PrivateSubnet1RouteTableId
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref Tgw
  ClientVpcPrivateSubnet2:
    Type: AWS::EC2::Route
    DependsOn: TgwAttachClientVpc
    Properties:
      RouteTableId:
        Fn::ImportValue: GitlabS3PoC-ClientVPC-PrivateSubnet2RouteTableId
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref Tgw
  #--
  GitlabVpCPrivateSubnet1:
    Type: AWS::EC2::Route
    DependsOn: TgwAttachGitlabVpc
    Properties:
      RouteTableId:
        Fn::ImportValue: GitlabS3PoC-GitlabVPC-PrivateSubnet1RouteTableId
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref Tgw
  GitlabVpCPrivateSubnet2:
    Type: AWS::EC2::Route
    DependsOn: TgwAttachGitlabVpc
    Properties:
      RouteTableId:
        Fn::ImportValue: GitlabS3PoC-GitlabVPC-PrivateSubnet2RouteTableId
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref Tgw
  #------------------ Route for VPC
  ExternalVpcPublicSubnet:
    Type: AWS::EC2::Route
    DependsOn: TgwAttachExternalVpc
    Properties:
      RouteTableId:
        Fn::ImportValue: GitlabS3PoC-ExternalVPC-PublicSubnetRouteTableId
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref Tgw